/* =========================================================
   SalimGPT
   File: js/documentary.js
   Purpose: Shared Documentary Article Controller
   Used by: All auto-generated documentary pages
   ---------------------------------------------------------
   RESPONSIBILITIES:
   - Bengali current year
   - Reading progress
   - Generated TOC navigation
   - Active TOC section
   - Smooth anchor scrolling
   - Share buttons
   - Copy-link buttons
   - YouTube/local image fallback
   - Related-card image fallback
   - Safe external links
   - Figure/image loading safety
   - Documentary ready event

   IMPORTANT:
   - Article content is generated by scripts/build.js
   - TOC is generated by scripts/build.js
   - Reading time is generated by scripts/build.js
   - This file does NOT invent documentary data
   - This file does NOT invent YouTube IDs
   ========================================================= */

(function () {
  "use strict";


  /* =======================================================
     01. BASIC HELPERS
     ======================================================= */

  const getById = (id) =>
    document.getElementById(id);


  const queryAll = (
    selector,
    scope = document
  ) =>
    Array.from(
      scope.querySelectorAll(selector)
    );


  function cleanText(value) {

    if (
      value === undefined ||
      value === null
    ) {
      return "";
    }


    return String(value).trim();
  }


  /* =======================================================
     02. BENGALI NUMBERS
     ======================================================= */

  const bengaliDigits = {
    "0": "०",
    "1": "१",
    "2": "२",
    "3": "३",
    "4": "४",
    "5": "५",
    "6": "६",
    "7": "७",
    "8": "८",
    "9": "९"
  };


  function toBengaliNumber(value) {

    return String(value).replace(
      /\d/g,
      (digit) =>
        bengaliDigits[digit]
    );
  }


  /* =======================================================
     03. CURRENT YEAR
     ======================================================= */

  function setCurrentYear() {

    const year =
      toBengaliNumber(
        new Date().getFullYear()
      );


    const targets = [
      getById("footerYear"),
      getById("menuYear")
    ];


    targets.forEach(
      (target) => {

        if (target) {
          target.textContent =
            year;
        }

      }
    );
  }


  /* =======================================================
     04. DOCUMENTARY ELEMENTS
     ======================================================= */

  function getDocumentaryArticle() {

    return document.querySelector(
      "[data-documentary-article]"
    );
  }


  function getDocumentaryBody() {

    return (
      document.querySelector(
        "[data-documentary-body]"
      ) ||
      getById(
        "documentaryArticle"
      )
    );
  }


  function getDocumentaryTitle() {

    const title =
      getById(
        "documentaryTitle"
      );


    if (title) {

      return cleanText(
        title.textContent
      );
    }


    return cleanText(
      document.title
        .replace(
          /\s*[—|-]\s*SalimGPT\s*$/i,
          ""
        )
    );
  }


  function getDocumentaryDescription() {

    const meta =
      document.querySelector(
        'meta[name="description"]'
      );


    return meta
      ? cleanText(
          meta.getAttribute(
            "content"
          )
        )
      : "";
  }


  /* =======================================================
     05. YOUTUBE ID EXTRACTION
     ======================================================= */

  function isValidYouTubeId(value) {

    return /^[A-Za-z0-9_-]{11}$/.test(
      cleanText(value)
    );
  }


  function extractYouTubeId(value) {

    const input =
      cleanText(value);


    if (!input) {
      return "";
    }


    if (
      isValidYouTubeId(input)
    ) {
      return input;
    }


    try {

      const url =
        new URL(
          input,
          window.location.href
        );


      const hostname =
        url.hostname
          .replace(
            /^www\./,
            ""
          )
          .toLowerCase();


      /*
        youtu.be/VIDEO_ID
      */

      if (
        hostname ===
        "youtu.be"
      ) {

        const id =
          url.pathname
            .split("/")
            .filter(Boolean)[0] ||
          "";


        return isValidYouTubeId(id)
          ? id
          : "";
      }


      /*
        youtube.com formats
      */

      if (
        hostname ===
          "youtube.com" ||
        hostname ===
          "m.youtube.com" ||
        hostname ===
          "music.youtube.com"
      ) {

        const watchId =
          url.searchParams.get("v");


        if (
          isValidYouTubeId(
            watchId
          )
        ) {

          return watchId;
        }


        const parts =
          url.pathname
            .split("/")
            .filter(Boolean);


        const type =
          parts[0];

        const id =
          parts[1];


        if (
          [
            "shorts",
            "embed",
            "live"
          ].includes(type) &&
          isValidYouTubeId(id)
        ) {

          return id;
        }
      }

    } catch (error) {

      return "";
    }


    return "";
  }


  function getPageYouTubeId() {

    /*
      build.js already generates a real
      YouTube link when one exists.

      We derive the ID only from that real URL.
    */

    const youtubeLink =
      document.querySelector(
        [
          ".video-preview-link[href]",
          ".youtube-button[href]"
        ].join(",")
      );


    if (!youtubeLink) {
      return "";
    }


    return extractYouTubeId(
      youtubeLink.getAttribute(
        "href"
      )
    );
  }


  /* =======================================================
     06. GENERATED READING TIME
     ======================================================= */

  function initializeReadingTime() {

    const element =
      getById(
        "readingTime"
      );


    if (!element) {
      return;
    }


    /*
      Preferred:
      scripts/build.js already calculated
      reading time.

      Do not recalculate using a different
      algorithm in the browser.
    */

    const generated =
      element.hasAttribute(
        "data-generated-reading-time"
      );


    if (
      generated &&
      cleanText(
        element.textContent
      )
    ) {

      element.hidden =
        false;

      return;
    }


    /*
      Safety fallback only.
      This normally should never be needed.
    */

    const body =
      getDocumentaryBody();


    if (!body) {
      return;
    }


    const text =
      cleanText(
        body.innerText
      );


    if (!text) {

      element.hidden =
        true;

      return;
    }


    const words =
      text
        .replace(
          /\s+/g,
          " "
        )
        .split(" ")
        .filter(Boolean);


    const minutes =
      Math.max(
        1,
        Math.ceil(
          words.length /
          220
        )
      );


    element.textContent =
      `${toBengaliNumber(minutes)} मिनट`;


    element.hidden =
      false;
  }


  /* =======================================================
     07. READING PROGRESS
     ======================================================= */

  function initializeReadingProgress() {

    const progressBar =
      getById(
        "readingProgressBar"
      );


    const article =
      getDocumentaryArticle();


    if (
      !progressBar ||
      !article
    ) {
      return;
    }


    let framePending =
      false;


    function calculateProgress() {

      framePending =
        false;


      const rect =
        article.getBoundingClientRect();


      const articleTop =
        window.scrollY +
        rect.top;


      const articleHeight =
        article.offsetHeight;


      const viewportHeight =
        window.innerHeight;


      /*
        Reading range:
        article top
        →
        article bottom minus viewport
      */

      const start =
        articleTop;


      const end =
        Math.max(
          start + 1,
          articleTop +
          articleHeight -
          viewportHeight
        );


      const current =
        window.scrollY;


      let percentage;


      if (
        current <= start
      ) {

        percentage =
          0;

      } else if (
        current >= end
      ) {

        percentage =
          100;

      } else {

        percentage =
          (
            (
              current -
              start
            ) /
            (
              end -
              start
            )
          ) * 100;
      }


      percentage =
        Math.min(
          100,
          Math.max(
            0,
            percentage
          )
        );


      progressBar.style.width =
        `${percentage}%`;


      progressBar.setAttribute(
        "aria-valuenow",
        String(
          Math.round(
            percentage
          )
        )
      );
    }


    function scheduleUpdate() {

      if (
        framePending
      ) {
        return;
      }


      framePending =
        true;


      window.requestAnimationFrame(
        calculateProgress
      );
    }


    window.addEventListener(
      "scroll",
      scheduleUpdate,
      {
        passive: true
      }
    );


    window.addEventListener(
      "resize",
      scheduleUpdate,
      {
        passive: true
      }
    );


    window.addEventListener(
      "load",
      scheduleUpdate,
      {
        once: true
      }
    );


    calculateProgress();
  }


  /* =======================================================
     08. GENERATED TABLE OF CONTENTS
     ======================================================= */

  function getTocLinks() {

    return queryAll(
      '[data-toc-list] a[href^="#"]'
    );
  }


  function getTocSections() {

    const uniqueSections =
      new Map();


    getTocLinks().forEach(
      (link) => {

        const href =
          cleanText(
            link.getAttribute(
              "href"
            )
          );


        if (
          !href ||
          href === "#"
        ) {
          return;
        }


        let id;


        try {

          id =
            decodeURIComponent(
              href.slice(1)
            );

        } catch (error) {

          id =
            href.slice(1);
        }


        if (!id) {
          return;
        }


        const heading =
          getById(id);


        if (!heading) {
          return;
        }


        if (
          !uniqueSections.has(id)
        ) {

          uniqueSections.set(
            id,
            heading
          );
        }

      }
    );


    return Array.from(
      uniqueSections.entries()
    ).map(
      ([id, heading]) => ({
        id,
        heading
      })
    );
  }


  function initializeTableOfContents() {

    /*
      TOC HTML is generated by build.js.

      JavaScript does NOT rebuild it.
      This prevents template H2/H3 elements
      from accidentally becoming documentary
      chapters.
    */

    const desktopToc =
      getById(
        "documentaryToc"
      );


    const mobileToc =
      document.querySelector(
        "[data-mobile-toc]"
      );


    const sections =
      getTocSections();


    if (
      !sections.length
    ) {

      /*
        build.js may intentionally show:
        "এই ডকুমেন্টারিতে আলাদা অধ্যায় শিরোনাম নেই"

        Keep that generated message visible.
      */

      if (
        desktopToc
      ) {

        desktopToc.classList.add(
          "toc-has-no-sections"
        );
      }


      if (
        mobileToc
      ) {

        mobileToc.classList.add(
          "toc-has-no-sections"
        );
      }


      return;
    }


    if (
      desktopToc
    ) {

      desktopToc.classList.remove(
        "toc-has-no-sections"
      );
    }


    if (
      mobileToc
    ) {

      mobileToc.classList.remove(
        "toc-has-no-sections"
      );
    }
  }


  /* =======================================================
     09. ACTIVE TOC SECTION
     ======================================================= */

  function initializeActiveToc() {

    const sections =
      getTocSections();


    if (
      !sections.length
    ) {
      return;
    }


    const links =
      getTocLinks();


    function setActiveSection(
      activeId
    ) {

      links.forEach(
        (link) => {

          const href =
            cleanText(
              link.getAttribute(
                "href"
              )
            );


          let linkId =
            "";


          if (
            href.startsWith("#")
          ) {

            try {

              linkId =
                decodeURIComponent(
                  href.slice(1)
                );

            } catch (error) {

              linkId =
                href.slice(1);
            }
          }


          const isActive =
            linkId ===
            activeId;


          link.classList.toggle(
            "is-active",
            isActive
          );


          if (
            isActive
          ) {

            link.setAttribute(
              "aria-current",
              "location"
            );

          } else {

            link.removeAttribute(
              "aria-current"
            );
          }

        }
      );
    }


    let framePending =
      false;


    function updateActiveSection() {

      framePending =
        false;


      /*
        Header-safe reading position.
      */

      const referenceY =
        150;


      let currentSection =
        sections[0];


      sections.forEach(
        (section) => {

          const top =
            section.heading
              .getBoundingClientRect()
              .top;


          if (
            top <= referenceY
          ) {

            currentSection =
              section;
          }

        }
      );


      setActiveSection(
        currentSection.id
      );
    }


    function scheduleUpdate() {

      if (
        framePending
      ) {
        return;
      }


      framePending =
        true;


      window.requestAnimationFrame(
        updateActiveSection
      );
    }


    window.addEventListener(
      "scroll",
      scheduleUpdate,
      {
        passive: true
      }
    );


    window.addEventListener(
      "resize",
      scheduleUpdate,
      {
        passive: true
      }
    );


    updateActiveSection();
  }


  /* =======================================================
     10. SMOOTH ANCHOR SCROLL
     ======================================================= */

  function initializeAnchorLinks() {

    document.addEventListener(
      "click",
      (event) => {

        const link =
          event.target.closest(
            'a[href^="#"]'
          );


        if (!link) {
          return;
        }


        const href =
          cleanText(
            link.getAttribute(
              "href"
            )
          );


        if (
          !href ||
          href === "#"
        ) {
          return;
        }


        let targetId;


        try {

          targetId =
            decodeURIComponent(
              href.slice(1)
            );

        } catch (error) {

          targetId =
            href.slice(1);
        }


        const target =
          getById(
            targetId
          );


        if (!target) {
          return;
        }


        event.preventDefault();


        const reduceMotion =
          window.matchMedia(
            "(prefers-reduced-motion: reduce)"
          ).matches;


        target.scrollIntoView({
          behavior:
            reduceMotion
              ? "auto"
              : "smooth",

          block:
            "start"
        });


        /*
          Keep URL fragment useful for
          copying/back navigation.
        */

        try {

          history.pushState(
            null,
            "",
            `#${encodeURIComponent(
              targetId
            )}`
          );

        } catch (error) {

          /*
            Ignore environments that do
            not allow History API.
          */
        }


        /*
          Mobile TOC closes after selection.
        */

        const details =
          link.closest(
            "details"
          );


        if (
          details &&
          details.open
        ) {

          details.open =
            false;
        }

      }
    );
  }


  /* =======================================================
     11. CLIPBOARD HELPER
     ======================================================= */

  async function copyText(value) {

    const text =
      cleanText(value);


    if (!text) {
      return false;
    }


    /*
      Modern secure-context API.
    */

    if (
      navigator.clipboard &&
      window.isSecureContext
    ) {

      try {

        await navigator.clipboard
          .writeText(text);


        return true;

      } catch (error) {

        /*
          Continue to legacy fallback.
        */
      }
    }


    /*
      Fallback for some mobile browsers /
      local preview environments.
    */

    const textarea =
      document.createElement(
        "textarea"
      );


    textarea.value =
      text;


    textarea.setAttribute(
      "readonly",
      ""
    );


    textarea.style.position =
      "fixed";

    textarea.style.opacity =
      "0";

    textarea.style.pointerEvents =
      "none";

    textarea.style.left =
      "-9999px";


    document.body.appendChild(
      textarea
    );


    textarea.select();

    textarea.setSelectionRange(
      0,
      textarea.value.length
    );


    let copied =
      false;


    try {

      copied =
        document.execCommand(
          "copy"
        );

    } catch (error) {

      copied =
        false;
    }


    textarea.remove();


    return copied;
  }


  /* =======================================================
     12. BUTTON LABEL HELPERS
     ======================================================= */

  function setTemporaryLabel(
    button,
    selector,
    temporaryText,
    duration = 1600
  ) {

    if (!button) {
      return;
    }


    const label =
      button.querySelector(
        selector
      );


    if (!label) {
      return;
    }


    const original =
      cleanText(
        label.textContent
      );


    label.textContent =
      temporaryText;


    button.classList.add(
      "is-success"
    );


    window.setTimeout(
      () => {

        label.textContent =
          original;


        button.classList.remove(
          "is-success"
        );

      },
      duration
    );
  }


  /* =======================================================
     13. COPY LINK BUTTONS
     ======================================================= */

  function initializeCopyButtons() {

    const buttons =
      queryAll(
        "[data-copy-button]"
      );


    if (
      !buttons.length
    ) {
      return;
    }


    buttons.forEach(
      (button) => {

        button.addEventListener(
          "click",
          async () => {

            const copied =
              await copyText(
                window.location.href
              );


            if (
              copied
            ) {

              setTemporaryLabel(
                button,
                "[data-copy-label]",
                "कॉपी हो गया"
              );


              button.setAttribute(
                "aria-label",
                "डॉक्यूमेंट्री का लिंक कॉपी हो गया"
              );


              window.setTimeout(
                () => {

                  button.setAttribute(
                    "aria-label",
                    "डॉक्यूमेंट्री का लिंक कॉपी करें"
                  );

                },
                1600
              );
            }

          }
        );

      }
    );
  }


  /* =======================================================
     14. SHARE BUTTONS
     ======================================================= */

  function initializeShareButtons() {

    const buttons =
      queryAll(
        "[data-share-button]"
      );


    if (
      !buttons.length
    ) {
      return;
    }


    const shareData = {

      title:
        getDocumentaryTitle(),

      text:
        getDocumentaryDescription(),

      url:
        window.location.href

    };


    buttons.forEach(
      (button) => {

        button.addEventListener(
          "click",
          async () => {

            /*
              Native mobile share.
            */

            if (
              typeof navigator.share ===
              "function"
            ) {

              try {

                await navigator.share(
                  shareData
                );


                return;

              } catch (error) {

                /*
                  User manually closed
                  share sheet.
                */

                if (
                  error &&
                  error.name ===
                    "AbortError"
                ) {

                  return;
                }


                /*
                  Other errors fall through
                  to copy-link fallback.
                */
              }
            }


            /*
              Browser does not support
              Web Share API:
              copy URL instead.
            */

            const copied =
              await copyText(
                window.location.href
              );


            if (
              copied
            ) {

              setTemporaryLabel(
                button,
                "[data-share-label]",
                "लिंक कॉपी हो गया",
                1800
              );
            }

          }
        );

      }
    );
  }


  /* =======================================================
     15. IMAGE FALLBACK CHAIN
     ======================================================= */

  function initializeImageFallbacks() {

    const images =
      queryAll(
        [
          "img[data-youtube-fallback]",
          "img[data-local-fallback]"
        ].join(",")
      );


    images.forEach(
      (image) => {

        if (
          image.dataset
            .documentaryFallbackBound ===
          "true"
        ) {
          return;
        }


        image.dataset
          .documentaryFallbackBound =
          "true";


        image.addEventListener(
          "error",
          () => {

            const currentSrc =
              cleanText(
                image.getAttribute(
                  "src"
                )
              );


            const youtubeFallback =
              cleanText(
                image.dataset
                  .youtubeFallback
              );


            const localFallback =
              cleanText(
                image.dataset
                  .localFallback
              );


            /*
              STEP 1:
              YouTube maxres failed
              → YouTube hqdefault
            */

            if (
              youtubeFallback &&
              image.dataset
                .youtubeFallbackUsed !==
                "true" &&
              currentSrc !==
                youtubeFallback
            ) {

              image.dataset
                .youtubeFallbackUsed =
                "true";


              image.src =
                youtubeFallback;


              return;
            }


            /*
              STEP 2:
              YouTube fallback failed
              → uploaded local image
            */

            if (
              localFallback &&
              image.dataset
                .localFallbackUsed !==
                "true" &&
              currentSrc !==
                localFallback
            ) {

              image.dataset
                .localFallbackUsed =
                "true";


              image.src =
                localFallback;


              return;
            }


            /*
              STEP 3:
              All real sources failed.

              No fake placeholder.
            */

            image.classList.add(
              "image-load-failed"
            );


            image.setAttribute(
              "aria-hidden",
              "true"
            );


            const container =
              image.closest(
                [
                  ".video-preview",
                  ".documentary-cover-frame",
                  ".related-card"
                ].join(",")
              );


            if (
              container
            ) {

              container.classList.add(
                "image-unavailable"
              );
            }

          }
        );

      }
    );
  }


  /* =======================================================
     16. ARTICLE FIGURES
     ======================================================= */

  function initializeArticleFigures() {

    const body =
      getDocumentaryBody();


    if (!body) {
      return;
    }


    const figures =
      queryAll(
        "figure",
        body
      );


    figures.forEach(
      (
        figure,
        index
      ) => {

        figure.dataset
          .figureIndex =
          String(
            index + 1
          );


        const image =
          figure.querySelector(
            "img"
          );


        if (!image) {
          return;
        }


        /*
          Generated attributes are preferred.
          These are only safety defaults.
        */

        if (
          !image.hasAttribute(
            "decoding"
          )
        ) {

          image.decoding =
            "async";
        }


        if (
          !image.hasAttribute(
            "loading"
          )
        ) {

          image.loading =
            "lazy";
        }

      }
    );
  }


  /* =======================================================
     17. EXTERNAL LINK SAFETY
     ======================================================= */

  function initializeExternalLinks() {

    const article =
      getDocumentaryArticle();


    if (!article) {
      return;
    }


    const links =
      queryAll(
        "a[href]",
        article
      );


    links.forEach(
      (link) => {

        const href =
          cleanText(
            link.getAttribute(
              "href"
            )
          );


        if (
          !href ||
          href.startsWith("#") ||
          href.startsWith("mailto:") ||
          href.startsWith("tel:")
        ) {
          return;
        }


        try {

          const url =
            new URL(
              href,
              window.location.href
            );


          if (
            url.origin !==
            window.location.origin
          ) {

            link.target =
              "_blank";


            link.rel =
              "noopener noreferrer";
          }

        } catch (error) {

          /*
            Invalid/unusual relative link:
            leave unchanged.
          */
        }

      }
    );
  }


  /* =======================================================
     18. YOUTUBE LINK SAFETY
     ======================================================= */

  function initializeYouTubeLinks() {

    const links =
      queryAll(
        [
          ".video-preview-link[href]",
          ".youtube-button[href]"
        ].join(",")
      );


    links.forEach(
      (link) => {

        const id =
          extractYouTubeId(
            link.getAttribute(
              "href"
            )
          );


        /*
          Do not create or modify fake URLs.
        */

        if (!id) {
          return;
        }


        link.target =
          "_blank";


        link.rel =
          "noopener noreferrer";

      }
    );
  }


  /* =======================================================
     19. INITIAL HASH POSITION
     ======================================================= */

  function initializeInitialHash() {

    const hash =
      cleanText(
        window.location.hash
      );


    if (
      !hash ||
      hash === "#"
    ) {
      return;
    }


    let id;


    try {

      id =
        decodeURIComponent(
          hash.slice(1)
        );

    } catch (error) {

      id =
        hash.slice(1);
    }


    const target =
      getById(id);


    if (!target) {
      return;
    }


    /*
      Browser may initially position before
      all fonts/images settle.
    */

    window.setTimeout(
      () => {

        target.scrollIntoView({
          behavior:
            "auto",

          block:
            "start"
        });

      },
      80
    );
  }


  /* =======================================================
     20. DOCUMENTARY READY EVENT
     ======================================================= */

  function dispatchReadyEvent() {

    document.dispatchEvent(
      new CustomEvent(
        "salimgpt:documentaryReady",
        {
          detail: {

            title:
              getDocumentaryTitle(),

            slug:
              cleanText(
                document.body
                  .dataset
                  .documentary
              ),

            date:
              cleanText(
                document.body
                  .dataset
                  .documentaryDate
              ),

            youtubeId:
              getPageYouTubeId()

          }
        }
      )
    );
  }


  /* =======================================================
     21. INITIALIZE
     ======================================================= */

  function initializeDocumentaryPage() {

    setCurrentYear();


    /*
      Trust build-generated article data.
    */

    initializeReadingTime();


    /*
      Reading/navigation.
    */

    initializeReadingProgress();

    initializeTableOfContents();

    initializeActiveToc();

    initializeAnchorLinks();

    initializeInitialHash();


    /*
      User actions.
    */

    initializeCopyButtons();

    initializeShareButtons();


    /*
      Media/link safety.
    */

    initializeImageFallbacks();

    initializeArticleFigures();

    initializeExternalLinks();

    initializeYouTubeLinks();


    /*
      Page ready state.
    */

    document.documentElement
      .classList.add(
        "documentary-ready"
      );


    dispatchReadyEvent();
  }


  /* =======================================================
     22. START
     ======================================================= */

  if (
    document.readyState ===
    "loading"
  ) {

    document.addEventListener(
      "DOMContentLoaded",
      initializeDocumentaryPage,
      {
        once: true
      }
    );

  } else {

    initializeDocumentaryPage();
  }

})();